### ISSUE TITLE
check persistence of data in $HOME

### ISSUE THREAD

**Issue by rpwagner** [cheapandfair/cheapandfair-gateways-2024#11]
Make sure things like `~/.cheapandfair.json` persist when user containers are restarted in JupyterHub

**Comment by rpwagner** [comment]
@zonca We should move files needed to be persisted to `~/work`, like the token file. This will probably mean passing a parameter to `git` to find the SSH key.

```
(base) jovyan@eaa409ad7973:~/work$ echo 'foo' >  ~/.cheapandfair.json
(base) jovyan@eaa409ad7973:~/work$ ls -a ~/
.  ..  .bash_logout  .bashrc  .cache  .cheapandfair.json  .conda  .config  .ipython  .jupyter  .local  .npm  .profile  work
```

After shutting down the my server and logging back in

```
(base) jovyan@454c4e2f4df4:~/work$ ls -a ~/
.  ..  .bash_logout  .bashrc  .cache  .conda  .config  .ipython  .jupyter  .local  .npm  .profile  work
```

**Comment by zonca** [comment]
I was expecting the entire home folder of the user to be inside a persistent volume

**Comment by zonca** [comment]
When I deploy on jet stream it is the entire home folder which is persistent.

So I think you can change the configuration of Jupiter hub fix this.

**Comment by rpwagner** [comment]
The [typical pattern](https://jupyterhub-dockerspawner.readthedocs.io/en/latest/data-persistence.html) is to have `work` be persistent. I'll try making the home directory persistent and see what changes.

**Comment by rpwagner** [comment]
If you the example JupyterHub config from JetStream to compare that could help

**Comment by rpwagner** [comment]
do you have anything critical on the hub right now? this will require me deleting the current volumes

**Comment by zonca** [comment]
I am deploying under kubernetes so the configuration of the spawner is different

**Comment by zonca** [comment]
Delete everything

**Comment by rpwagner** [comment]
OK, it's working. I wasn't sure how the home directory was handled since it gets loaded from the container image initially. I though the volume might mount over it.

**Comment by rpwagner** [comment]
fixed
