### ISSUE TITLE
Sunday morning runthrough

### ISSUE THREAD

**Issue by zonca** [cheapandfair/cheapandfair-gateways-2024#15]

**Comment by zonca** [comment]
new github account https://github.com/cheapandfair-tester

new account was marked as spam and could not link to globus.

testing with another account I have which is not my main one: https://github.com/zoncaoverleafbot

**Comment by zonca** [comment]
taking the last collection in the list:

ff57fadd-9bc8-4b92-b161-9d34ebf4d094  Cheap and FAIR Tutorial Collection Barnacle

**Comment by zonca** [comment]
was able to do "Login" -> "Login with Github" on Globus and created new Globus account.

**Comment by zonca** [comment]
requested membership to group and approved myself from my main account

**Comment by zonca** [comment]
JupyterHub link: https://srdr-jh.cheapandfair.org/

**Comment by zonca** [comment]
@rpwagner created short link https://bit.ly/srdr24
the orignal link is:

https://srdr-jh.cheapandfair.org/hub/user-redirect/git-pull?repo=https://github.com/cheapandfair/cheapandfair-gateways-2024&urlpath=lab/tree/cheapandfair-gateways-2024/1_github_pages.ipynb&branch=main

**Comment by zonca** [comment]
@rpwagner nbgitpuller did not work, no errors, just empty folder. anyway I'll continue.
Given we need attendees to configure `gh` anyway, we could do a quick clone.

- [ ] fix nbgitpuller

**Comment by zonca** [comment]
persistent works as expected, I stopped my server, logged in again got JHub and `gh` had stored my credentials.

**Comment by rpwagner** [comment]
Nbgitpuller was working for me last night. I’ll be on my laptop in about 30 minutes and check again.

**Comment by zonca** [comment]
> Nbgitpuller was working for me last night. I’ll be on my laptop in about 30 minutes and check again.

no hurry, I'm going forward with the run-through

**Comment by zonca** [comment]
@rpwagner is this steps from notebook 2 necessary to login to JupyterHub?

- [ ] if so this should go into slides before notebook 1.

![image](https://github.com/user-attachments/assets/1e3b6144-9025-47f7-8894-75035e92f9c2)

**Comment by rpwagner** [comment]
> @rpwagner is this steps from notebook 2 necessary to login to JupyterHub?
> 
> * [ ]  if so this should go into slides before notebook 1.
> 
> ![image](https://private-user-images.githubusercontent.com/383090/371874464-1e3b6144-9025-47f7-8894-75035e92f9c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MzA5NzIsIm5iZiI6MTcyNzYzMDY3MiwicGF0aCI6Ii8zODMwOTAvMzcxODc0NDY0LTFlM2I2MTQ0LTkwMjUtNDdmNy04ODk0LTc1MDM1ZTkyZjljMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQxNzI0MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYmM1YWI0MzNiYjlmM2NkNzA0MDE4N2IxZDRjYjVhYWJkMmViYzRkYzk2ZGVkOGRhNjM2NGMzYTJlMGZlYzBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.73PPXyVdZM8mLJlnBbJrhz4_rE8hF-d2Z5F_u0jzVi8)

Yes, access to JupyterHub is limited to folks in that Group. I was think we should post a short note in the README here of pre-work like

> ## Pre-Work
> 
> - Create a GitHub account if you don't already have one.
> - If you already have a Globus account, [link your GitHub identity](https://docs.globus.org/guides/tutorials/manage-identities/link-to-existing/).
> - If you're new to Globus, [login to Globus](https://app.globus.org/).
> - You can select GitHub on the Globus login page.
> - After you have logged in, request to join the [Cheap and FAIR Tutorial Users](https://app.globus.org/groups/fad784e0-67dd-11ef-87ff-09715fb135c2/about) Globus Group. This will allow you to access the JupyterHub server.

We can reference that in an email we send later today.

**Comment by rpwagner** [comment]
@zonca try this link for nbgitpuller. There's a `/jhub/` at the top of the URL.

https://srdr-jh.cheapandfair.org/jhub/hub/user-redirect/git-pull?repo=https://github.com/cheapandfair/cheapandfair-gateways-2024&urlpath=lab/tree/cheapandfair-gateways-2024/1_github_pages.ipynb&branch=main

**Comment by zonca** [comment]
@rpwagner I'm not manager of the guest collections,
can you give permissions on https://app.globus.org/file-manager/collections/ff57fadd-9bc8-4b92-b161-9d34ebf4d094/overview

to zonca@globus and zoncaoverleafbot@github?

**Comment by zonca** [comment]
@rpwagner `toml` is missing from the docker image:
https://github.com/cheapandfair/globus-jupyter-notebook/releases/tag/2024-09-29

**Comment by zonca** [comment]
> @rpwagner I'm not manager of the guest collections, can you give permissions on https://app.globus.org/file-manager/collections/ff57fadd-9bc8-4b92-b161-9d34ebf4d094/overview
> 
> to zonca@globus and zoncaoverleafbot@github?

nevermind, I just needed to login with zonca@github

**Comment by rpwagner** [comment]
> > @rpwagner I'm not manager of the guest collections, can you give permissions on https://app.globus.org/file-manager/collections/ff57fadd-9bc8-4b92-b161-9d34ebf4d094/overview
> > to zonca@globus and zoncaoverleafbot@github?
> 
> nevermind, I just needed to login with zonca@github

I also made `zonca@globusid.org` an admin on the mapped collection, so you can manage all of the guest collections.

https://app.globus.org/file-manager/collections/af8c6369-f74c-4d43-9b43-72d45c74f1b0/shares

**Comment by rpwagner** [comment]
> @rpwagner `toml` is missing from the docker image: https://github.com/cheapandfair/globus-jupyter-notebook/releases/tag/2024-09-29

The images weren't updating automatically. I'll update the config and then I may need to remove the previous version.

**Comment by rpwagner** [comment]
> > @rpwagner `toml` is missing from the docker image: https://github.com/cheapandfair/globus-jupyter-notebook/releases/tag/2024-09-29
> 
> The images weren't updating automatically. I'll update the config and then I may need to remove the previous version.

It's currently tracking `main` so it updated automatically. We should probably stick with that for today and then set it to a particular release when we're done.

**Comment by zonca** [comment]
created new nbgitpuller link https://bit.ly/srdr-24

**Comment by zonca** [comment]
ok, went through all content except notebook 7.
Looks good,
I will do another quick one tomorrow mornign before tutorial mostly to test nbgitpuller.

https://github.com/cheapandfair/cheapandfair-gateways-2024/pull/16
