### ISSUE TITLE
Clean up before tutorial?

### ISSUE THREAD

**Issue by rpwagner** [cheapandfair/cheapandfair-gateways-2024#19]
@zonca Do you want me to remove the volume for your test account so it's fresh tomorrow?

```
DRIVER    VOLUME NAME
local     jupyterhub-user-rpwagner
local     jupyterhub-user-zoncaoverleafbot
```

You can also remove the data & permissions from the Guest Collection and the template repo if you want everything the same as the students.

https://app.globus.org/file-manager?origin_id=ff57fadd-9bc8-4b92-b161-9d34ebf4d094&origin_path=%2F

https://github.com/zoncaoverleafbot/cheapandfair-template

**Comment by zonca** [comment]
Yes please

**Comment by rpwagner** [comment]
Done. And you're also an admin in JupyterHub so you can stop user servers if needed.
